language: node_js
node_js:
 - node
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - steven.burton@emishealth.com
services:
  - mongodb
  - docker
addons:
  apt:
    packages:
    - python-pip
before_install:
  - pip install --upgrade --user awscli
  - chmod +x deploy/docker-push.sh
  - chmod +x deploy/ecs-deploy
  - chmod +x deploy/ecs-deploy.sh
install:
  - npm install
  - npm install newman -g
  - npm install pkill -g
script:
  - npm run newman-server
  - docker build -t uppeat .
after_failure:
  - deploy/docker-push.sh
  - deploy/ecs-deploy.sh