notifications:
email:
  recipients:
    - steven.burton@emishealth.com
  on_success: always
  on_failure: always
services:
  - mongodb
before_install:
  - npm install
  - npm install newman -g
install: true
language: node_js
node_js:
 - node
script:
  - npm run newman-server