notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - steven.burton@emishealth.com
services:
  - mongodb
  - docker
before_install:
  - npm install
  - npm install newman -g
install: true
language: node_js
node_js:
 - node
script:
  - npm run newman-server
after_script:
  - docker build