language: node_js
node_js:
 - node
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - steven.burton@emishealth.com
services:
  - mongodb
  - docker
addons:
  apt:
    packages:
    - python-pip
before_install:
  - pip install --upgrade --user awscli
install:
  - npm install
  - npm install newman -g
  - npm install pkill -g
script:
  - npm run newman-server
  - docker build -t uppeat .
after_failure:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    export PATH=$PATH:$HOME/.local/bin;
    eval $(aws ecr get-login --no-include-email --region eu-west-2);
    docker tag uppeat:latest 236542331794.dkr.ecr.eu-west-2.amazonaws.com/uppeat:latest;
    docker push 236542331794.dkr.ecr.eu-west-2.amazonaws.com/uppeat:latest;
    fi