language: node_js
node_js:
 - node
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - steven.burton@emishealth.com
services:
  - mongodb
  - docker
install:
  - npm install
  - npm install newman -g
script:
  - npm run newman-server
after_script:
  - docker build .