language: node_js
node_js:
 - node
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - steven.burton@emishealth.com
services:
  - mongodb
  - docker
before_install:
  - apt-get update
  - apt-get -y install python-pip
  - pip install --upgrade --user awscli
install:
  - npm install
  - npm install curl -g
  - npm install newman -g
  - npm install pkill -g
script:
  - npm run newman-server
  - docker build -t steveburton4/uppeat:latest .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push steveburton4/uppeat;
    fi
after_failure:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    aws ecr get-login --no-include-email --region us-east-1;
    export PATH=$PATH:$HOME/.local/bin;
    docker login -u AWS -p $AWS_PASSWORD -e none https://236542331794.dkr.ecr.us-east-1.amazonaws.com
    docker tag uppeat:latest 236542331794.dkr.ecr.us-east-1.amazonaws.com/uppeat:latest;
    docker push 236542331794.dkr.ecr.us-east-1.amazonaws.com/uppeat:latest;
    fi