version: '2.0'
services:
  api:
    image: steveburton4/uppeat:latest
    container_name: api
    ports:
      - "54321:54321"
    environment:
      NODE_ENV: production
      MONGODB_ADDRESS: database
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo:latest
    container_name: database
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null