version: '2.0'
services:
  api:
    build: .
    container_name: api
    ports:
      - "54321:54321"
    environment:
      NODE_ENV: development
      MONGODB_ADDRESS: database
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo:latest
    container_name: database
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
  test:
    image: postman/newman_ubuntu1404
    links:
      - api
    depends_on:
      - api
      - database
    volumes:
      - .:/etc/newman
    command: "run /etc/newman/test/postman/UpPeat.postman_collection.json -e /etc/newman/test/postman/localhost.postman_environment.json --reporter-html-export results.html"